# my-portfolio-os/docker-compose.yml
version: "3.8"

services:
  web:
    build: .
    ports:
      - "3003:3004"
    volumes:
      - node_modules_volume:/app/node_modules
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./.env
    depends_on:
      - db
    command: [ "npm", "start" ]

  db:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongo_data:
  node_modules_volume:
